# Generated by Django 6.0.2 on 2026-02-03 20:34

import teams.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Team',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('city', models.CharField(max_length=100)),
                ('year_founded', models.PositiveIntegerField(blank=True, null=True)),
                ('logo', models.ImageField(blank=True, null=True, upload_to='', validators=[teams.validators.LogoValidator(2)])),
                ('coach_name', models.CharField(blank=True, max_length=100)),
            ],
        ),
    ]
