# Generated by Django 6.0.2 on 2026-02-05 18:15

import teams.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='teams/', validators=[teams.validators.LogoValidator(2)]),
        ),
    ]
