# Generated by Django 6.0.2 on 2026-03-11 10:34

import django.core.validators
import teams.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('teams', '0003_alter_team_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='logo',
            field=models.ImageField(blank=True, default='defaults/team.png', upload_to='teams/', validators=[teams.validators.LogoValidator(2)]),
        ),
        migrations.AlterField(
            model_name='team',
            name='year_founded',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1900), django.core.validators.MaxValueValidator(2026)]),
        ),
    ]
