# Generated by Django 6.0.2 on 2026-02-13 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='award',
            name='title',
            field=models.CharField(choices=[('MVP', 'Most Valuable Player'), ('MIP', 'Most Improved Player'), ('DPOY', 'Defensive Player of the Year'), ('REB', 'Rebounder of the Year'), ('SCORING', 'Scoring Title'), ('ASSIST', 'Assist Champion')], max_length=100),
        ),
    ]
