# Generated by Django 6.0.2 on 2026-02-19 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0002_alter_award_title'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='award',
            unique_together={('title', 'year')},
        ),
    ]
