# Generated by Django 6.0.2 on 2026-02-12 14:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0002_remove_game_players_gameplayerstats'),
        ('players', '0002_player_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='game',
            name='players',
            field=models.ManyToManyField(related_name='games', through='games.GamePlayerStats', to='players.player'),
        ),
    ]
