# Generated by Django 6.0.2 on 2026-02-18 18:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('games', '0003_game_players'),
        ('players', '0002_player_photo'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='gameplayerstats',
            unique_together={('game', 'player')},
        ),
    ]
